import Head from "next/head";
import {
  Group,
  Container,
  Textarea,
  Grid,
  Center,
  Blockquote,
  Space,
  Title,
  Text,
} from "@mantine/core";
import { useState } from "react";
import ReactMarkdown from "react-markdown";
import { GoMarkdown } from "react-icons/go";
import RichTextEditor from "../components/RichText";

export default function Home() {
  // const [colorScheme, setColorScheme] = useState("light");
  const [value, onChange] = useState(
    "<p>Your initial <b>html value</b> or an empty string to init editor without value</p>"
  );
  const [markdown, setMarkdown] = useState("Leave a comment");

  return (
    <>
      <Container size="xl">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* Main section*/}
        <Group position="center">
          {/* Header */}
          <h1>
            <Title transform="uppercase">
              Markdown Previewer with Next.js and Mantine
            </Title>
            <Text color="red">++Rich Text Editor</Text>
          </h1>
        </Group>
        <Space h="xl" />
        {/* Body */}
        <Grid justify="space-around" align="flex-start" columns={2}>
          <Grid.Col span={1}>
            <div>
              <Text
                weight={600}
                transform="uppercase"
                align="center"
                component="span"
                variant="gradient"
                gradient={{ from: "indigo", to: "cyan", deg: 45 }}
                style={{ fontFamily: "Greycliff CF, sans-serif" }}
              >
                Write a Markdown
              </Text>
              <Textarea
                placeholder={markdown}
                required
                onChange={(e) => setMarkdown(e.target.value)}
              />
              <Group spacing={4}>
                <GoMarkdown size={20} />
                <Text size="sm" weight={400}>
                  Styling with Markdown is supported
                </Text>
              </Group>
            </div>
          </Grid.Col>
          <Grid.Col span={1}>
            <div>
              <Text
                weight={600}
                transform="uppercase"
                align="center"
                component="span"
                variant="gradient"
                gradient={{ from: "indigo", to: "cyan", deg: 45 }}
                style={{ fontFamily: "Greycliff CF, sans-serif" }}
              >
                Markdown Preview
              </Text>
              <ReactMarkdown>{markdown}</ReactMarkdown>
            </div>
          </Grid.Col>
        </Grid>

        <Space h="xl" />

        <Text
          weight={600}
          transform="uppercase"
          align="center"
          component="span"
          variant="gradient"
          gradient={{ from: "indigo", to: "cyan", deg: 45 }}
          style={{ fontFamily: "Greycliff CF, sans-serif" }}
        >
          Rich Text Editor
        </Text>
        <RichTextEditor />

        {/* Footer section */}
        <Space h="xl" />
        <Center>
          <Blockquote cite="– Nineria">
            Don't cross that bridge till you come to it.
          </Blockquote>
        </Center>
      </Container>
    </>
  );
}
